### ISSUE TITLE
Logging in for first time since user deleted in Sanity threw error

### ISSUE THREAD

**Issue by readeral** [Vision100IT/pwad.org.au#32]
The following error threw in the console trying to log in for the first time since my user details were wiped in sanity. I wasn't successfully logged in. Subsequent attempt did login however:

```

ServerError: Internal server error
    at onResponse (/Users/readeral/Development/New Front Door/pwad.org.au/node_modules/@sanity/client/lib/http/request.js:25:13)
    at /Users/readeral/Development/New Front Door/pwad.org.au/node_modules/get-it/lib-node/util/middlewareReducer.js:10:22
    at Array.reduce (<anonymous>)
    at applyMiddleware (/Users/readeral/Development/New Front Door/pwad.org.au/node_modules/get-it/lib-node/util/middlewareReducer.js:9:29)
    at onResponse (/Users/readeral/Development/New Front Door/pwad.org.au/node_modules/get-it/lib-node/index.js:81:22)
    at /Users/readeral/Development/New Front Door/pwad.org.au/node_modules/get-it/lib-node/index.js:48:55
    at callback (/Users/readeral/Development/New Front Door/pwad.org.au/node_modules/get-it/lib-node/request/node-request.js:57:46)
    at /Users/readeral/Development/New Front Door/pwad.org.au/node_modules/get-it/lib-node/request/node-request.js:141:14
    at DestroyableTransform.<anonymous> (/Users/readeral/Development/New Front Door/pwad.org.au/node_modules/simple-concat/index.js:7:13)
    at Object.onceWrapper (events.js:427:28)
    at DestroyableTransform.emit (events.js:333:22)
    at endReadableNT (/Users/readeral/Development/New Front Door/pwad.org.au/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  response: {
    body: { error: [Object] },
    url: 'https://w0mujm5q.api.sanity.io/v1/data/mutate/production?returnIds=true&returnDocuments=true&visibility=sync',
    method: 'POST',
    headers: {
      'content-type': 'application/json; charset=utf-8',
      'content-length': '73',
      date: 'Wed, 05 Feb 2020 10:25:09 GMT',
      vary: 'Origin',
      xkey: 'project-w0mujm5q, project-w0mujm5q-production',
      via: '1.1 google',
      'alt-svc': 'clear',
      connection: 'close'
    },
    statusCode: 500,
    statusMessage: 'Internal Server Error'
  },
  statusCode: 500,
  responseBody: '{\n' +
    '  "error": {\n' +
    '    "description": "Internal server error",\n' +
    '    "type": "internalError"\n' +
    '  }\n' +
    '}',
  details: { description: 'Internal server error', type: 'internalError' }
}

```

**Comment by readeral** [comment]
Likely an artifact of the interaction between auth0 and sanity that won't be replicated. Closing issue.
