### ISSUE TITLE
Scripture Rubrics fail to load

### ISSUE THREAD

**Issue by readeral** [Vision100IT/pwad.org.au#34]
Navigate to [scripture rubrics](http://localhost:3000/content/eaeb8225-7a90-4a27-aab8-3f427f4076b0) - select an option - console outputs the following:

```
Error while running `getDataFromTree` ApolloError: GraphQL error: Cannot return null for non-nullable field PageContent._id.
    at new ApolloError (/Users/readeral/Development/New Front Door/pwad.org.au/node_modules/apollo-client/bundle.umd.js:92:26)
    at /Users/readeral/Development/New Front Door/pwad.org.au/node_modules/apollo-client/bundle.umd.js:1588:34
    at /Users/readeral/Development/New Front Door/pwad.org.au/node_modules/apollo-client/bundle.umd.js:2008:15
    at Set.forEach (<anonymous>)
    at /Users/readeral/Development/New Front Door/pwad.org.au/node_modules/apollo-client/bundle.umd.js:2006:26
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/Users/readeral/Development/New Front Door/pwad.org.au/node_modules/apollo-client/bundle.umd.js:2004:20)
    at /Users/readeral/Development/New Front Door/pwad.org.au/node_modules/apollo-client/bundle.umd.js:2131:19
    at Object.next (/Users/readeral/Development/New Front Door/pwad.org.au/node_modules/zen-observable/lib/Observable.js:308:23)
    at notifySubscription (/Users/readeral/Development/New Front Door/pwad.org.au/node_modules/zen-observable/lib/Observable.js:130:18)
    at onNotify (/Users/readeral/Development/New Front Door/pwad.org.au/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.next (/Users/readeral/Development/New Front Door/pwad.org.au/node_modules/zen-observable/lib/Observable.js:219:7)
    at /Users/readeral/Development/New Front Door/pwad.org.au/node_modules/apollo-client/bundle.umd.js:1102:36
    at Set.forEach (<anonymous>)
    at Object.next (/Users/readeral/Development/New Front Door/pwad.org.au/node_modules/apollo-client/bundle.umd.js:1101:21)
    at notifySubscription (/Users/readeral/Development/New Front Door/pwad.org.au/node_modules/zen-observable/lib/Observable.js:130:18) {
  graphQLErrors: [
    {
      message: 'Cannot return null for non-nullable field PageContent._id.',
      locations: [Array],
      path: [Array],
      extensions: [Object]
    }
  ],
  networkError: null,
  message: 'GraphQL error: Cannot return null for non-nullable field PageContent._id.',
  extraInfo: undefined
```

**Comment by BarryThePenguin** [comment]
Appears to work ok...

http://pwad.now.sh/content/eaeb8225-7a90-4a27-aab8-3f427f4076b0

I have seen weird things where the content is in draft state in sanity. Publishing it fixes the issue

**Comment by readeral** [comment]
Did you click on a rubric link?

**Comment by BarryThePenguin** [comment]
Sorry, it wasn't obvious from the link or description you provided

The Scripture pages don't exist

https://pwad.now.sh/scripture/73246830-3acf-4d3d-834f-063adb823b52

**Comment by readeral** [comment]
lol: "Navigate to scripture rubrics - **select an option**"

**Comment by BarryThePenguin** [comment]
![](https://media.giphy.com/media/3o6ZtlGESaunB5qKf6/giphy.gif)

**Comment by BarryThePenguin** [comment]
Looks like it's sorted now 👍 

pwad.now.sh/scripture/73246830-3acf-4d3d-834f-063adb823b52

**Comment by readeral** [comment]
Great job
